/**
 * users.js — Danh sách user dùng chung cho tất cả scripts
 * Đồng bộ với admin-login-tool.html (file HTML vẫn hardcode riêng)
 *
 * Khi thêm user mới, cập nhật CẢ file này VÀ admin-login-tool.html
 */

const USERS = [
  { name: 'Quán Nhậu Galaxy',              phone: '862019199',  email: 'quannhaugalaxy@gmail.com',       address: 'Thôn 3 - Thạch Hòa - Thạch Thất' },
  { name: 'Ghiền BBQ',                      phone: '0372311859', email: 'quachmanhloc1999@gmail.com',     address: 'Thôn 3 - Thạch Hòa - Thạch Thất' },
  { name: 'MANYO Tteokbokki Hoà Lạc',       phone: '0977567833', email: 'manyohoalac@gmail.com',          address: 'Tân Xã - Hòa Lạc' },
  { name: 'HaBi Streets Cuisine - Hoà Lạc', phone: '0398900026', email: '',                               address: 'Thôn 3 - Thạch Hòa - Thạch Thất' },
  { name: '1988 BBQ',                        phone: '0329656565', email: '1988bbq1@gmail.com',             address: 'Thôn 3 - Thạch Hòa - Thạch Thất' },
  { name: 'Bánh tráng Tana',                phone: '0975533159', email: 'sieuthibanhtrangtana@gmail.com', address: 'Thôn 3 - Thạch Hòa - Thạch Thất' },
  { name: 'Nhất Nướng Quán',                phone: '0985372989', email: '',                               address: 'Thôn 3 - Thạch Hòa - Thạch Thất' },
  { name: 'Cơm Gà Ruby',                    phone: '0966378633', email: 'Ngocthuytiin@gmail.com',         address: 'Thôn 3 - Thạch Hòa - Thạch Thất' },
  { name: 'Sweet Cake Tân Xã',              phone: '0334678158', email: '',                               address: 'Tân Xã - Hòa Lạc' },
  { name: 'Cơm rang Nguyễn Việt',           phone: '356721667',  email: '',                               address: 'Thôn 3 - Thạch Hòa - Thạch Thất' },
  { name: 'Young Food&Drink',               phone: '0335990484', email: '',                               address: 'Tân Xã - Hòa Lạc' },
  { name: 'Lẩu nướng 368',                  phone: '977625684',  email: 'giakhang842009@gmail.com',       address: 'Thôn 3 - Thạch Hòa - Thạch Thất' },
  { name: 'Nem nướng Hùng Anh',             phone: '342436528',  email: '',                               address: 'Thôn 3 - Thạch Hòa - Thạch Thất' },
  { name: 'Trung Toàn Bakery',              phone: '0338893388', email: '',                               address: 'Hòa Lạc, Bình Yên, Thạch Thất, Hà Nội' },
  { name: 'Thành Phát Bakery Hoà Lạc',      phone: '0906066585', email: '',                               address: 'Hòa Lạc, Bình Yên, Thạch Thất, Hà Nội' },
  { name: 'Taetna Hoà Lạc',                 phone: '968478816',  email: '',                               address: 'Thạch Hòa - Thạch Thất' },
  { name: 'Hằng Nguyễn bakery',             phone: '962288790',  email: '',                               address: 'Ngã tư lục quân, Hòa lạc' },
  { name: 'Chè ngon Jolly',                 phone: '0869958939', email: '',                               address: 'Thôn 3 Thạch Hòa' },
  { name: 'Techno Tea',                     phone: '326392618',  email: '',                               address: 'Thôn 3 - Thạch Hòa - Thạch Thất' },
  { name: 'Takocha',                        phone: '0343857996', email: '',                               address: 'Thôn 3 - Thạch Hòa - Thạch Thất' },
  { name: 'Bún Cá Nam Hà',                  phone: '966707009',  email: '',                               address: 'Hòa Lạc, Bình Yên, Thạch Thất, Hà Nội' },
  { name: 'Barbershop Hoà Lạc',             phone: '389369202',  email: '',                               address: 'Hòa Lạc, Bình Yên, Thạch Thất, Hà Nội' },
  { name: 'Tiên An Costumes',               phone: '929745666',  email: '',                               address: 'Hòa Lạc, Bình Yên, Thạch Thất, Hà Nội' },
  { name: 'Phở Nam Nhất',                   phone: '385748668',  email: '',                               address: 'Cầu Hòa Lạc, Bình Yên, Thạch Thất, Hà Nội' },
  { name: "Loan's Pickleball",              phone: '0989419586', email: '',                               address: 'Ngõ 5 Cụm 4 Thôn 3 Thạch Hòa' },
  { name: 'Qin Hair Salon',                 phone: '0983071566', email: '',                               address: 'Thôn 3 Hòa Lạc' },
  { name: 'Liên Facial Spa',                phone: '0395769189', email: '',                               address: 'Thôn 3 Hòa Lạc' },
  { name: 'Bún Chả Thu Hà',                 phone: '0898243680', email: '',                               address: 'Thôn 3 Hòa Lạc' },
  { name: 'Bún Bò Huế Đức Duy',             phone: '0973271135', email: '',                               address: 'Thôn 3 Hòa Lạc' },
  { name: 'Quán Ăn Đêm Tuấn Hằng',          phone: '0964495509', email: '',                               address: 'Thôn 2 Hòa Lạc' },
  { name: 'Bún Cá Thái Bình',               phone: '0901513669', email: '',                               address: 'Thôn 2 Hòa Lạc' },
  { name: 'Lẩu Nướng 368',                  phone: '0977625684', email: '',                               address: 'Ngã 3 Hòa lạc' },
  { name: 'Quán meo meo phở bò cơm rang',   phone: '0981890636', email: '',                               address: 'Thôn 4 Thạch Hòa' },
  { name: 'Yên Bái Quán',                   phone: '0879952398', email: '',                               address: 'Thôn 3 Thạch Hòa' },
  { name: 'Cơm sạch 17',                    phone: '0822783123', email: '',                               address: 'Thôn 3 Thạch Hòa' },
  { name: 'Hẻm Nướng 1978',                 phone: '0327127277', email: '',                               address: 'Thôn 3 Thạch Hòa' },
  { name: 'Cơm Xe Tải Thanh Huyền',         phone: '0987746158', email: '',                               address: 'Gần ngã tư đhqg' },
  { name: 'Cơm Nguyễn Tuấn',                phone: '0983556183', email: '',                               address: 'Ngã 3 Hòa lạc' },
  { name: 'Cơm Tấm Chính Lan 1998',         phone: '0368466998', email: '',                               address: 'Tân Xã - Hòa Lạc' },
  { name: 'Thiên Ban Quán Bún Cá Cay',      phone: '0968860363', email: '',                               address: 'tân Xã - Hòa Lạc' },
  { name: 'Mây Quán',                       phone: '0862261226', email: '',                               address: 'đường hoàng tùng, lê trọng tấn, an khánh hà nội' },
  { name: 'Tiêm Cơm Gia Đinh Hà Đông',      phone: '0965730550', email: '',                               address: 'Khu B Geleximco, Lê Trọng Tấn, An Khánh, Hà Nội' },
  { name: 'Cơm Ngon Anh Béo',               phone: '0968251516', email: '',                               address: 'Khu B Geleximco, An Khánh, Hà Nội' },
  { name: 'Tiệm Cơm Nàng Tấm',              phone: '0839103388', email: '',                               address: 'Khu đô thị Geleximco, Lê Trọng Tấn, Tây Mỗ, Hà Nội' },
  { name: 'Bún Đậu Thủy Gà',                phone: '0985102468', email: '',                               address: '201 Lê Trọng Tấn, La Dương, Dương Nội, Hà Nội' },
  { name: 'Tít Thò Lò',                     phone: '0972895533', email: '',                               address: '18AB, Dương Nội, Hà Nội' },
  { name: 'Cháo Mr.Bean',                   phone: '0862655924', email: '',                               address: 'Lê Giản, Đại Mỗ, Hà Nội, Vietnam' },
  { name: 'Tiệm Bánh Thu Trang',            phone: '0936290932', email: '',                               address: '49 P. Ngọc Trục, làng Ngọc Trục, Đại Mỗ, Hà Nội' },
  { name: "MỲ CAY LA'CA",                   phone: '0989251931', email: '',                               address: '40 P. Ngọc Trục, làng Ngọc Trục, Đại Mỗ, Hà Nội' },
  { name: 'Chân Gà Sốt Thái MeeChang',      phone: '0336789071', email: '',                               address: '93 Ngọc Trục, làng Ngọc Trục, Đại Mỗ, Hà Nội' },
  { name: 'Chất Lẩu Nướng Buffet',          phone: '0969158193', email: '',                               address: '48 Vườn Cam, Từ Liêm, Hà Nội' },
  { name: 'Quán nhậu Trang Trẻ Trâu',       phone: '0968598771', email: '',                               address: '6 P. Hồng Đô, làng Phú Đô, Từ Liêm, Hà Nội' },
  { name: 'Bia hơi minh tâm',               phone: '0836484333', email: '',                               address: '31 Đ. Mễ Trì, Từ Liêm, Hà Nội' },
  { name: 'Phở Thìn Mỹ Đình',               phone: '02432006379', email: '',                              address: 'CT9 Mỹ Đình Sông Đà, Từ Liêm, Hà Nội' },
  { name: 'Quán Tươi',                      phone: '0974356725', email: '',                               address: '3 Ngõ 123 Trung Kính, Yên Hòa, Hà Nội' },
  { name: 'Cơm Văn Đô Trung Kính',          phone: '0356922789', email: '',                               address: '58 P. Trung Kính, Yên Hòa, Hà Nội' },
  { name: 'KienKo Kitchen',                 phone: '0779222029', email: '',                               address: '34 P. Trung Kính, Yên Hòa, Hà Nội' },
  { name: 'Bún riêu tóp mỡ 37',             phone: '0961013130', email: '',                               address: '67 P. Trung Kính, Yên Hòa, Hà Nội' },
  { name: 'Đụt Quán',                       phone: '0868128180', email: '',                               address: '5 Ngõ 41 Trần Duy Hưng, Yên Hòa, Hà Nội' },
  { name: 'Quán Cơm Hữu Toàn',                     phone: 'TX7001', email: '', address: 'ĐT419, Tây Phương, Hà Nội, Vietnam' },
  { name: 'Cà Phê Bùng',                           phone: '0979735489', email: '', address: '98 ĐT419, Thôn Bùng, Tây Phương, Hà Nội' },
  { name: 'Bún Bò Huế Thảo My',                    phone: 'TX7002', email: '', address: 'ĐT419, Tây Phương, Hà Nội, Vietnam' },
  { name: 'Quán Cơm Bống',                         phone: '0393691682', email: '', address: 'ĐT419, Tây Phương, Hà Nội, Vietnam' },
  { name: 'Chè Hằng',                              phone: '0582683683', email: '', address: 'Đ. Trường Học, Tây Phương, Hà Nội' },
  { name: 'Trạm Trà Kami',                         phone: 'TX7008', email: '', address: 'Cổng Đông, Tây Phương, Hà Nội' },
  { name: 'Bún Đậu Mắm Tôm Thanh Lan',             phone: '0973085381', email: '', address: 'Đường Cổng Đình, Tây Phương, Hà Nội' },
  { name: 'Nhà Của An',                            phone: '0965204686', email: '', address: '40 Đường Cổng Kết, Vĩnh Lộc, Tây Phương, Hà Nội' },
  { name: 'Lẩu ếch Hồng Kiên',                     phone: '0978714387', email: '', address: 'Xóm 2, Vĩnh Lộc, Tây Phương, Hà Nội' },
  { name: 'Tiệm bánh mình Hiếu',                   phone: 'TX7004', email: '', address: 'Đường Cổng Nùi, Vĩnh Lộc, Tây Phương, Hà Nội' },
  { name: 'Dingtea Hữu Bằng',                      phone: '0836672672', email: '', address: 'Đ. Trường Học, Tây Phương, Hà Nội' },
  { name: 'MINH HÓM',                              phone: '01234567890', email: '', address: '' },
  { name: 'Hair & Beauty ĐạtG',                    phone: '0867793883', email: '', address: 'Xóm 3, Vĩnh Lộc, Tây Phương, Hà Nội' },
  { name: 'Nhà Hàng Thịt Chó Phạm Hiệp',           phone: 'TX7003', email: '', address: '94 Đường 419 Phùng Xá, Tây Phương, Hà Nội' },
  { name: 'Nủa Coffee',                            phone: '0908586226', email: '', address: '24 Đ. Ủy Ban, Tây Phương, Hà Nội' },
  { name: 'Bún Cá Quả Sơn Tây',                    phone: '0387021593', email: '', address: '79 Đ. Trường Học, Hữu Bằng, Hà Nội' },
  { name: 'The led tiệm Trà Chanh',                phone: '0985402728', email: '', address: 'ĐT419, Tây Phương, Hà Nội, Vietnam' },
  { name: 'Vườn Xoài Quán',                        phone: '0916898505', email: '', address: 'ĐT419, Tây Phương, Hà Nội, Vietnam' },
  { name: 'Guu Chicken',                           phone: '0987565940', email: '', address: '28 Đ. Trường Học, Tây Phương, Hà Nội' },
  { name: 'ZICO HAIR',                             phone: '0385874468', email: '', address: '30 Đ. Trường Học, Tây Phương, Hà Nội' },
  { name: 'Buffet Chay Happy',                     phone: '0966306361', email: '', address: '59 Liên Xã, Tây Phương, Hà Nội' },
  { name: 'Ăn Vặt Mẹ Sữa',                         phone: '02462944588', email: '', address: '79 Đ. Trường Học, Tây Phương, Hà Nội' },
  { name: 'Quán ăn vặt Chu Chu',                   phone: 'TX7005', email: '', address: 'Đường Cổng Đình, Tây Phương, Hà Nội' },
  { name: 'Kong Buffet Lẩu Nướng Thạch Thất',      phone: '0948868767', email: '', address: 'ĐT419, Tây Phương, Hà Nội, Vietnam' },
  { name: 'Ngọc Thạch Quán Hữu Bằng',              phone: 'TX7006', email: '', address: '50 Đ. Trường Học, Tây Phương, Hà Nội' },
  { name: 'BBQ Thu Hương Phan',                    phone: '0945588673', email: '', address: 'Đ. Trường Học, Tây Phương, Hà Nội' },
  { name: 'Nhà Hàng Gà Mạnh Hoạch Phùng Xá',       phone: '0977586848', email: '', address: 'ĐT419, Tây Phương, Hà Nội, Vietnam' },
  { name: 'Bún Ngan Huyền Thương',                 phone: '0971244563', email: '', address: 'ĐT419, Tây Phương, Hà Nội, Vietnam' },
  { name: 'Huy Béo Quán',                          phone: '0989601924', email: '', address: 'ĐT419, Tây Phương, Hà Nội, Vietnam' },
  { name: 'Tiệm Bánh Nguyễn Huệ',                  phone: 'TX7011', email: '', address: '38 Đập Đồng Bùi, Tây Phương, Hà Nội, Vietnam' },
  { name: 'Ánh Lành Makeup',                       phone: '0981601298', email: '', address: '37 Xóm 1, Vĩnh Lộc, Tây Phương, Hà Nội' },
  { name: 'Phở Gà Mây Thương Thương',              phone: 'TX7009', email: '', address: 'Xóm Rừng Mây, Vĩnh Lộc, Tây Phương, Hà Nội' },
  { name: 'Quán Phở Hoàng Nam',                    phone: 'TX7010', email: '', address: '' },
  { name: 'Quán Phở Mạnh Tiến',                    phone: '0366342755', email: '', address: 'Đường Cổng Kết, Vĩnh Lộc, Tây Phương, Hà Nội' },
  { name: 'Ếch Xanh Thạch Thất',                   phone: '0337421879', email: '', address: '11 Đường 419 Phùng Xá, Tây Phương, Hà Nội' },
  { name: 'Cơm bình dân Hải Lan',                  phone: '0383507796', email: '', address: 'ĐT419, Cống Sông Bùng, Tây Phương, Hà Nội' },
  { name: 'Hiếu Trí - Bún Bò Huế',                 phone: 'TX7007', email: '', address: 'Đ. Trường Học, Tây Phương, Hà Nội' },
  { name: 'Phở Bờm',                               phone: '0966985581', email: '', address: 'ĐT419, Tây Phương, Hà Nội, Vietnam' },
  { name: 'Next Xu Cafe 2',                        phone: '0983195612', email: '', address: 'Cổng Đông, Tây Phương, Hà Nội' },
  { name: 'Phở Gà Nhớ',                            phone: '0946373383', email: '', address: '96 Đường Đa Khoa, Tây Phương, Hà Nội' },
  { name: 'Vừng Quán',                             phone: '0393289777', email: '', address: 'KCN Yên Bình, Thái Nguyên' },
  { name: 'Thùy Dương Healthy',                    phone: '0862818893', email: '', address: 'Khu Bãi Bông, Phổ Yên, Thái Nguyên' },
  { name: 'Quán Bia Bằng Chưa',                    phone: '0974956061', email: '', address: 'Đào Xá Nghĩa Dân, Hưng Yên' },
  { name: 'Cafe Hoa',                              phone: '0934686815', email: '', address: '63 Ngõ 12 Khuất Duy Tiến, Thanh Xuân, Hà Nội' },
  { name: 'Cá Kho Nguyễn Cường',                   phone: '0973465074', email: '', address: 'Chợ KTX Sam Sung, Thái Nguyên' },
  { name: 'Bếp Gạo Bắp',                           phone: '0966709748', email: '', address: 'Số 49 Ng. 47 P. Khương Trung, Khương Đình, Hà Nội' },
  { name: 'Bánh Sinh Nhật Nhung Nhung',            phone: '0962393064', email: '', address: 'Khu Lê Hồng Phong, Thái Nguyên' },
  { name: 'Barber Shop - Cắt Tóc Nam',             phone: '0372353098', email: '', address: '23 ĐT196, Phố Nối, Mỹ Hào, Hưng Yên' },
  { name: 'Xưa Quán',                              phone: '0976558332', email: '', address: '126 Đường Minh Cầu, TP. Thái Nguyên' },
  { name: 'Bún Miến Ngan Thái Hà',                 phone: '0912443125', email: '', address: 'Ngõ 1, Đường Minh Cầu, Phan Đình Phùng, TP. Thái Nguyên' },
  { name: 'Kiều Gác Bếp',                          phone: '0975269763', email: '', address: 'Xóm Trung, Điềm Thụy, Thái Nguyên' },
  { name: 'Bi\'s Flame Pizza',                      phone: '0862058822', email: '', address: '342 Thống Nhất, Phan Đình Phùng, Thái Nguyên' },
  { name: 'K-Express - Pizza Chicken',             phone: '0988554112', email: '', address: '132 Phan Đình Phùng, TP. Thái Nguyên' },
  { name: 'Lẩu Nướng Sapa',                        phone: '0977068886', email: '', address: 'Trung tâm thương mại, Việt Tiến, Hưng Yên' },
  { name: 'Bún Chả Ngọc Bích',                     phone: '0982355346', email: '', address: 'Xóm Trung, Điềm Thụy, Thái Nguyên' },
  { name: 'Cơm Tấm Sài Gòn',                       phone: '0987835594', email: '', address: '1b P. Đại Từ, Định Công, Hà Nội' },
  { name: 'Cafe Giang',                            phone: '0362740465', email: '', address: '16 Quang Trung, Hà Đông, Hà Nội' },
  { name: 'Bún Đậu Mẹt Thu Béo',                   phone: '0983849887', email: '', address: '103 E13, KTT Thanh Xuân Bắc, Thanh Xuân, Hà Nội' },
  { name: 'Tiệm Bánh Ngọt Và Trà Hoa Lụa',         phone: '0975881223', email: '', address: 'Ngõ 45 Minh Cầu, TP. Thái Nguyên' },
  { name: 'Nét Cuốn',                              phone: '0357727919', email: '', address: '30 P. Nguyễn Văn Lộc, KĐT Bắc Hà, Hà Đông, Hà Nội' },
  { name: 'PHỞ BÒ CỒ CHẤT 3',                      phone: '0979769140', email: '', address: 'QL39A, Việt Tiến, Hưng Yên' },
  { name: 'Tiệm Bánh Mỳ Que 105E2',                phone: '0913576633', email: '', address: '105-E2 P. Thái Thịnh, Đống Đa, Hà Nội' },
  { name: 'Spa Loan',                              phone: '0780048201', email: '', address: 'Xóm Chùa, Đồng Trúc, Tây Phương, Hà Nội' },
  { name: 'Bánh Mì Dân Tổ Thái Nguyên',            phone: '0968221445', email: '', address: '52 Hoàng Văn Thụ, TP. Thái Nguyên' },
  { name: 'Jun Hair Salon',                        phone: '0383833835', email: '', address: '58C Hoàng Hoa Thám, Phan Đình Phùng, Thái Nguyên' },
  { name: 'Quán Ăn Sơn Phát',                      phone: '0788752741', email: '', address: '79 Trần Bình, Nghĩa Đô, Cầu Giấy, Hà Nội' },
  { name: 'Hair & Beauty Yến Thịnh',               phone: '0812968708', email: '', address: '32 Nghĩa Đô, Nghĩa Đô, Cầu Giấy, Hà Nội' },
  { name: 'Phở Nam Định',                          phone: '0984408367', email: '', address: 'Nghĩa Dân, Hưng Yên' },
  { name: 'Sửa Chữa Xe Máy Huy Hùng',              phone: '0987105566', email: '', address: 'Đào Xá Nghĩa Dân, Hưng Yên' },
  { name: 'Trạm Trà Kami',                         phone: 'TX9002', email: '', address: 'Cổng Đông, Tây Phương, Hà Nội' },
  { name: 'Bún Cô Thắng (Bún Riêu Bún Dọc Mùng)',  phone: '0397213540', email: '', address: '94 Ng. 521 Đ. Trương Định, Hoàng Mai, Hà Nội' },
  { name: 'Quán Nướng Dũng',                       phone: '0388811863', email: '', address: '163 Tô Hiệu, Nghĩa Đô, Cầu Giấy, Hà Nội' },
  { name: 'Thanh Nhung Bakery',                    phone: '0983452114', email: '', address: 'Cổng Trường ĐH Nông Lâm, TP. Thái Nguyên' },
  { name: 'Hair & Beauty Bình Phạm',               phone: '0913274535', email: '', address: '85 Nguyễn Trãi, Hà Đông, Hà Nội' },
  { name: 'Cao Quán - Hải Sản & Ốc Xào',           phone: '0984665221', email: '', address: 'Ngã ba Bắc Nam, TP. Thái Nguyên' },
  { name: 'Phở Trộn & Phở Cuốn Hà Nội',            phone: '0989112344', email: '', address: '68 Quang Trung, TP. Thái Nguyên' },
  { name: 'Bia Hơi TỒ CON',                        phone: '0386936368', email: '', address: '129 P. Giáp Nhị, Giáp Nhị, Hoàng Mai, Hà Nội' },
  { name: 'Bakery Quốc Đại',                       phone: '0389570851', email: '', address: '87 Đường Lương Thế Vinh, Phan Đình Phùng, Thái Nguyên' },
  { name: 'Bún Chả Sinh Từ 2',                     phone: '0382119553', email: '', address: 'Thôn Đa Ngưu, Xã Tân Tiến, Văn Giang, Hưng Yên' },
  { name: 'Phở Cổ',                                phone: '0326855421', email: '', address: 'QL39A, Bô Thời, Việt Tiến, Hưng Yên' },
  { name: 'Trâu Giật Hưng Mạnh',                   phone: '0975441552', email: '', address: 'Khu Hoàng Gia, Tân Thịnh, TP. Thái Nguyên' },
  { name: 'Hands Barber Shop',                     phone: '0775347712', email: '', address: 'Đ. Cấp 3 Nghĩa Dân, Trương Xá, Hưng Yên' },
  { name: 'Wi Hair Salon',                         phone: '0973752739', email: '', address: 'Gần trường cao đẳng thuỷ lợi, Việt Tiến, Hưng Yên' },
  { name: 'Cẩm Vân Bakery',                        phone: '0369507915', email: '', address: '150 Đường Bắc Sơn, TP. Thái Nguyên' },
  { name: 'Tiệm Bánh Kem Paris Gateaux',           phone: '02435123888', email: '', address: '88 Lương Ngọc Quyến, TP. Thái Nguyên' },
  { name: 'Em Tài Food & Drink',                   phone: '0977128104', email: '', address: 'Cổng sau KCN Điềm Thụy, Thái Nguyên' },
  { name: 'KEN QUÁN',                              phone: '0966771221', email: '', address: 'Bô Thời, Việt Tiến, Hưng Yên' },
  { name: 'Cắt Tóc Minh Kiên',                     phone: '0868402900', email: '', address: '73 P. Nguyễn Chính, Hoàng Mai, Hà Nội' },
  { name: 'Tóc Nam 430',                           phone: '0868023069', email: '', address: '430 Đường CM Tháng Tám, KĐT Hồ Xương Rồng, TP. Thái Nguyên' },
  { name: 'Hoa Tươi Hồng Thắm',                    phone: '0964671482', email: '', address: '176 Đ. Kim Giang, Kim Văn, Định Công, Hà Nội' },
  { name: 'Quán Cơm Lâm An',                       phone: '0369482281', email: '', address: 'Thôn Tượng Cước, Xuân Trúc, Hưng Yên' },
  { name: 'Mì Cay Thanh Thi',                      phone: '0338696863', email: '', address: '270 Đường Việt Bắc, Thái Nguyên' },
  { name: 'Bánh Đa Ghẹ Sơn Béo',                   phone: '0902169186', email: '', address: 'Số 3k7, Ngõ 43 Nguyễn An Ninh, Tương Mai, Hà Nội' },
  { name: 'Vịt Quay Bình Phát',                    phone: '0975974232', email: '', address: 'Thôn Cẩm Cơ, Hồng Vân, Thường Tín, Hà Nội' },
  { name: 'Kim Bắp Thủy Tiên',                     phone: '0878541886', email: '', address: 'Đán, Thái Nguyên' },
  { name: 'Quán Cơm Cô Tấm',                       phone: '0359853389', email: '', address: 'Thôn Bảo Tàng, Xuân Trúc, Hưng Yên' },
  { name: 'Phở Gà Ta Minh Hằng',                   phone: '0915662445', email: '', address: '88 Phùng Chí Kiên, Trưng Vương, TP. Thái Nguyên' },
  { name: 'Ri.O Hair Salon',                       phone: '0981225220', email: '', address: '315 Đường Hoàng Văn Thụ, Phan Đình Phùng, Thái Nguyên' },
  { name: 'Ổ Bánh Mì - 85C Nguyễn Văn Tuyết',      phone: '0963056599', email: '', address: '85c Nguyễn Văn Tuyết, Đống Đa, Hà Nội' },
  { name: 'Bún Trộn Nam Bộ & Mì Trộn',             phone: '0965223114', email: '', address: '28 Hoàng Hoa Thám, TP. Thái Nguyên' },
  { name: 'Cơm Rang Thập Cẩm Chú Bẩy',             phone: '0392114887', email: '', address: 'Khu TT 226, P. Bạch Sam, TX Mỹ Hào, Hưng Yên' },
  { name: 'Cô Diệp Bánh Đa Cua Hải Phòng',         phone: '0984171616', email: '', address: 'Ngõ 622 P. Minh Khai, Vĩnh Tuy, Hà Nội' },
  { name: 'Khánh Barber Shop',                     phone: '0352717170', email: '', address: 'Cầu Mụa, Lương Bằng, Hưng Yên' },
  { name: 'Gội Đầu & Massage Sen Xanh',            phone: '0947380838', email: '', address: '81 Ng. 634 Đ. Kim Giang, Thanh Liệt, Hà Nội' },
  { name: 'Quang Tèo - Ốc Ngon',                   phone: '0964223558', email: '', address: 'Ngã Ba Bắc Nam, TP. Thái Nguyên' },
  { name: 'Spa An Quán',                           phone: '0964039891', email: '', address: 'Thôn Cơ Giáo, Hồng Vân, Thường Tín, Hà Nội' },
  { name: 'Vạn Gia Food',                          phone: '0904319194', email: '', address: 'KTT Thanh Xuân Bắc, Thanh Xuân, Hà Nội' },
  { name: 'Cơm Sườn Phố Cổ BBQ',                   phone: '0947309209', email: '', address: '241 Trần Đại Nghĩa, Bạch Mai, Hà Nội' },
  { name: 'Hoa Sáp Hà Nội',                        phone: '0399518131', email: '', address: '271/3 P. Bùi Xương Trạch, Khương Đình, Hà Nội' },
  { name: 'Cơm Bình Dân Anh Bốn',                  phone: '0964746850', email: '', address: 'QL39A, Nghĩa Dân, Hưng Yên' },
  { name: 'Tiệm bánh mình Hiếu',                   phone: 'TX9001', email: '', address: 'Đường Cổng Nùi, Vĩnh Lộc, Tây Phương, Hà Nội' },
  { name: 'Hair & Beauty Đức',                     phone: '0322816113', email: '', address: '6 Đường Đồng Trúc, Yên Lạc, Tây Phương, Hà Nội' },
  { name: 'Tiệm Trà Cô Ba',                        phone: '0868802176', email: '', address: 'Số nhà 13, Đường Quang Trung, Đồng Quang, TP. Thái Nguyên' },
  { name: 'Quán Cháo Dinh Dưỡng Minh Phúc',        phone: '0382180435', email: '', address: '48 P. Giáp Nhị, Giáp Nhị, Hoàng Mai, Hà Nội' },
  { name: 'Làng Nướng An Bình',                    phone: '0983554226', email: '', address: 'Khu dân cư số 5, P. Túc Duyên, TP. Thái Nguyên' },
  { name: 'Spa Kiên',                              phone: '0398456815', email: '', address: '42 Đường Cổng Đình, Vĩnh Lộc, Tây Phương, Hà Nội' },
  { name: 'Quán Lẩu Việt',                         phone: '0931318386', email: '', address: 'Trung tâm thương mại, Việt Tiến, Hưng Yên' },
  { name: 'Pate Đò Quan Nam Định',                 phone: '0989233930', email: '', address: 'Ngõ29/78 P. Khương Hạ, Khương Đình, Hà Nội' },
  { name: 'Hải Sản Minh Châu',                     phone: '0385186789', email: '', address: 'Phan Đình Phùng, TP. Thái Nguyên' },
  { name: 'Quán Ăn An',                            phone: '0333663560', email: '', address: 'Ngách 5, Đường Hoàng Quốc Việt 59, Nghĩa Đô, Cầu Giấy, Hà Nội' },
  { name: 'Shop Hoa Hồng Huệ',                     phone: '0984193096', email: '', address: '6 Nguyễn Hữu Thọ, Định Công, Hà Nội' },
  { name: 'Cắt Tóc Nam Đinh Nguyễn',               phone: '0961293100', email: '', address: '49 P. Giáp Nhị, Giáp Nhị, Hoàng Mai, Hà Nội' },
  { name: 'Cơm Bình Dân Tuyết Nhi',                phone: '0385090058', email: '', address: 'Xã Xuân Trúc, Cù Tu, Hưng Yên' },
  { name: 'Lẩu Mang Về - Lẩu Lòng Bò Chợ Viềng Food', phone: '0366533211', email: '', address: 'Chợ Đình Yên Khê, Việt Tiến, Hưng Yên' },
  { name: 'Gỏi Cá Định Công',                      phone: '0988869757', email: '', address: '477 Ng. 192 P. Lê Trọng Tấn, Định Công, Hà Nội' },
  { name: 'Shop Mẹ Và Bé Quỳnh',                   phone: '0835256778', email: '', address: 'Thôn La Thượng, Hồng Vân, Thường Tín, Hà Nội' },
  { name: 'Bếp Mẹ Na - Nem Nướng Nha Trang & Ăn Vặt', phone: '0972565633', email: '', address: '37 P. Bùi Huy Bích, Pháp Vân, Hoàng Mai, Hà Nội' },
  { name: 'Trà Chanh Đạt',                         phone: '0974366833', email: '', address: '38 Đường Đê Sông Hồng, La Thượng, Hồng Vân, Thường Tín, Hà Nội' },
  { name: 'Bánh Canh Cá Rô Đồng Nem Nướng Nha Trang', phone: '0986456788', email: '', address: '18 Ngõ 71 Nguyên Hồng, C9 P. Hoàng Ngọc Phách, Hà Nội' },
  { name: 'Bia Hơi Hà Nội',                        phone: '0375212170', email: '', address: 'QL39A, Việt Tiến, Hưng Yên' },
  { name: 'Quán cắt tóc trẻ con',                  phone: '033521122118', email: '', address: '' },
  { name: 'Sinh Anh Hair Salon Thái Nguyên',       phone: '0934519566', email: '', address: '450 Lương Ngọc Quyến, TP. Thái Nguyên' },
  { name: 'Cafe Hoa Thịnh',                        phone: '0794283394', email: '', address: 'Thôn Vân La, Hồng Vân, Thường Tín, Hà Nội' },
  { name: 'Tiệm Cơm Rang Đệ Nhất Khói',            phone: '0336114775', email: '', address: 'Thôn Lại Ốc, Xã Long Hưng, Văn Giang, Hưng Yên' },
  { name: 'Chân Gà Sốt Thái Thu Hương',            phone: '0989256155', email: '', address: '346 Bắc Sơn, Thái Nguyên' },
  { name: 'Gà Rán Yên',                            phone: '0345346218', email: '', address: 'Thôn Xâm Xuyên, Hồng Vân, Thường Tín, Hà Nội' },
  { name: 'TIỆM BÁNH MỲ CHẢO SỐ 7 TRẦN PHÚ',       phone: '0984109604', email: '', address: '7 Đ. Trần Phú, Thanh Liệt, Hà Nội' },
  { name: 'Cắt tóc Mạnh Dũng',                     phone: '033204004552', email: '', address: '' },
  { name: 'Cơm Bình Dân Sơn Thắm',                 phone: '0986013253', email: '', address: 'QL39A, Nghĩa Dân, Hưng Yên' },
  { name: 'Bánh Rán Khương Hạ - Bánh Mỳ Pate',     phone: '0979184424', email: '', address: '72 Ng. 29 P. Khương Hạ, Khương Đình, Hà Nội' },
  { name: 'Nộm Thanh Hà',                          phone: '0936327079', email: '', address: 'C21 Nguyễn Quý Đức, KTT Thanh Xuân Bắc, Hà Nội' },
  { name: 'Ăn Ngon Trà Phạm',                      phone: '0374996787', email: '', address: 'Phường Quyết Thắng, Thái Nguyên' },
  { name: 'Vườn Trúc Quán: Cơm, Phở, Bia, Lẩu',    phone: '0901032888', email: '', address: 'Khu CN số 5, Ngô Xá, Xuân Trúc, Hưng Yên' },
  { name: 'Hair & Beauty Huyền',                   phone: '0797602988', email: '', address: '39 Tô Hiệu, Hà Đông, Hà Nội' },
  { name: 'Mê Hải Sản',                            phone: '0869688688', email: '', address: '19 Đ. Láng, Đống Đa, Hà Nội' },
  { name: 'Nem Nướng My',                          phone: '0813122563', email: '', address: '114 Trần Bình, Nghĩa Đô, Cầu Giấy, Hà Nội' },
  { name: 'Quán Sửa Xe Máy',                       phone: '0379795976', email: '', address: 'Đạo Khê, Yên Mỹ, Hưng Yên' },
  { name: 'LINH ANH HEALTHY',                      phone: '0348301311', email: '', address: 'Xóm Trung, Điềm Thụy, Thái Nguyên' },
  { name: 'Phở Trần Gia - Chuyên Phở Gà',          phone: '0981144225', email: '', address: 'Ngã 4, Bô Thời, Việt Tiến, Hưng Yên' },
  { name: 'Nhà Của Diệp',                          phone: '0858326642', email: '', address: 'Xóm 1, Đồng Trúc, Tây Phương, Hà Nội' },
  { name: 'Nem Nướng Nha Trang Hà Anh',            phone: '0966404313', email: '', address: '103 Ngh. 98 Ng. Tự Do, Bạch Mai, Hà Nội' },
  { name: 'Vân Food',                              phone: '0965845225', email: '', address: 'Lộc Thượng Đinh, Thanh Xuân, Hà Nội' },
  { name: 'A Cường Hair Studio',                   phone: '0972554118', email: '', address: '144 Đường Việt Bắc, TP. Thái Nguyên' },
];

module.exports = USERS;
