/**
 * users.js — Danh sách user dùng chung cho tất cả scripts
 * Đồng bộ với admin-login-tool.html (file HTML vẫn hardcode riêng)
 *
 * Khi thêm user mới, cập nhật CẢ file này VÀ admin-login-tool.html
 */

const USERS = [
  { name: 'Quán Nhậu Galaxy',              phone: '862019199',  email: 'quannhaugalaxy@gmail.com',       address: 'Thôn 3 - Thạch Hòa - Thạch Thất' },
  { name: 'Ghiền BBQ',                      phone: '0372311859', email: 'quachmanhloc1999@gmail.com',     address: 'Thôn 3 - Thạch Hòa - Thạch Thất' },
  { name: 'MANYO Tteokbokki Hoà Lạc',       phone: '0977567833', email: 'manyohoalac@gmail.com',          address: 'Tân Xã - Hòa Lạc' },
  { name: 'HaBi Streets Cuisine - Hoà Lạc', phone: '0398900026', email: '',                               address: 'Thôn 3 - Thạch Hòa - Thạch Thất' },
  { name: '1988 BBQ',                        phone: '0329656565', email: '1988bbq1@gmail.com',             address: 'Thôn 3 - Thạch Hòa - Thạch Thất' },
  { name: 'Bánh tráng Tana',                phone: '0975533159', email: 'sieuthibanhtrangtana@gmail.com', address: 'Thôn 3 - Thạch Hòa - Thạch Thất' },
  { name: 'Nhất Nướng Quán',                phone: '0985372989', email: '',                               address: 'Thôn 3 - Thạch Hòa - Thạch Thất' },
  { name: 'Cơm Gà Ruby',                    phone: '0966378633', email: 'Ngocthuytiin@gmail.com',         address: 'Thôn 3 - Thạch Hòa - Thạch Thất' },
  { name: 'Sweet Cake Tân Xã',              phone: '0334678158', email: '',                               address: 'Tân Xã - Hòa Lạc' },
  { name: 'Cơm rang Nguyễn Việt',           phone: '356721667',  email: '',                               address: 'Thôn 3 - Thạch Hòa - Thạch Thất' },
  { name: 'Young Food&Drink',               phone: '0335990484', email: '',                               address: 'Tân Xã - Hòa Lạc' },
  { name: 'Lẩu nướng 368',                  phone: '977625684',  email: 'giakhang842009@gmail.com',       address: 'Thôn 3 - Thạch Hòa - Thạch Thất' },
  { name: 'Nem nướng Hùng Anh',             phone: '342436528',  email: '',                               address: 'Thôn 3 - Thạch Hòa - Thạch Thất' },
  { name: 'Trung Toàn Bakery',              phone: '0338893388', email: '',                               address: 'Hòa Lạc, Bình Yên, Thạch Thất, Hà Nội' },
  { name: 'Thành Phát Bakery Hoà Lạc',      phone: '0906066585', email: '',                               address: 'Hòa Lạc, Bình Yên, Thạch Thất, Hà Nội' },
  { name: 'Taetna Hoà Lạc',                 phone: '968478816',  email: '',                               address: 'Thạch Hòa - Thạch Thất' },
  { name: 'Hằng Nguyễn bakery',             phone: '962288790',  email: '',                               address: 'Ngã tư lục quân, Hòa lạc' },
  { name: 'Chè ngon Jolly',                 phone: '0869958939', email: '',                               address: 'Thôn 3 Thạch Hòa' },
  { name: 'Techno Tea',                     phone: '326392618',  email: '',                               address: 'Thôn 3 - Thạch Hòa - Thạch Thất' },
  { name: 'Takocha',                        phone: '0343857996', email: '',                               address: 'Thôn 3 - Thạch Hòa - Thạch Thất' },
  { name: 'Bún Cá Nam Hà',                  phone: '966707009',  email: '',                               address: 'Hòa Lạc, Bình Yên, Thạch Thất, Hà Nội' },
  { name: 'Barbershop Hoà Lạc',             phone: '389369202',  email: '',                               address: 'Hòa Lạc, Bình Yên, Thạch Thất, Hà Nội' },
  { name: 'Tiên An Costumes',               phone: '929745666',  email: '',                               address: 'Hòa Lạc, Bình Yên, Thạch Thất, Hà Nội' },
  { name: 'Phở Nam Nhất',                   phone: '385748668',  email: '',                               address: 'Cầu Hòa Lạc, Bình Yên, Thạch Thất, Hà Nội' },
  { name: "Loan's Pickleball",              phone: '0989419586', email: '',                               address: 'Ngõ 5 Cụm 4 Thôn 3 Thạch Hòa' },
  { name: 'Qin Hair Salon',                 phone: '0983071566', email: '',                               address: 'Thôn 3 Hòa Lạc' },
  { name: 'Liên Facial Spa',                phone: '0395769189', email: '',                               address: 'Thôn 3 Hòa Lạc' },
  { name: 'Bún Chả Thu Hà',                 phone: '0898243680', email: '',                               address: 'Thôn 3 Hòa Lạc' },
  { name: 'Bún Bò Huế Đức Duy',             phone: '0973271135', email: '',                               address: 'Thôn 3 Hòa Lạc' },
  { name: 'Quán Ăn Đêm Tuấn Hằng',          phone: '0964495509', email: '',                               address: 'Thôn 2 Hòa Lạc' },
  { name: 'Bún Cá Thái Bình',               phone: '0901513669', email: '',                               address: 'Thôn 2 Hòa Lạc' },
  { name: 'Lẩu Nướng 368',                  phone: '0977625684', email: '',                               address: 'Ngã 3 Hòa lạc' },
  { name: 'Quán meo meo phở bò cơm rang',   phone: '0981890636', email: '',                               address: 'Thôn 4 Thạch Hòa' },
  { name: 'Yên Bái Quán',                   phone: '0879952398', email: '',                               address: 'Thôn 3 Thạch Hòa' },
  { name: 'Cơm sạch 17',                    phone: '0822783123', email: '',                               address: 'Thôn 3 Thạch Hòa' },
  { name: 'Hẻm Nướng 1978',                 phone: '0327127277', email: '',                               address: 'Thôn 3 Thạch Hòa' },
  { name: 'Cơm Xe Tải Thanh Huyền',         phone: '0987746158', email: '',                               address: 'Gần ngã tư đhqg' },
  { name: 'Cơm Nguyễn Tuấn',                phone: '0983556183', email: '',                               address: 'Ngã 3 Hòa lạc' },
  { name: 'Cơm Tấm Chính Lan 1998',         phone: '0368466998', email: '',                               address: 'Tân Xã - Hòa Lạc' },
  { name: 'Thiên Ban Quán Bún Cá Cay',      phone: '0968860363', email: '',                               address: 'tân Xã - Hòa Lạc' },
  { name: 'Mây Quán',                       phone: '0862261226', email: '',                               address: 'đường hoàng tùng, lê trọng tấn, an khánh hà nội' },
  { name: 'Tiêm Cơm Gia Đinh Hà Đông',      phone: '0965730550', email: '',                               address: 'Khu B Geleximco, Lê Trọng Tấn, An Khánh, Hà Nội' },
  { name: 'Cơm Ngon Anh Béo',               phone: '0968251516', email: '',                               address: 'Khu B Geleximco, An Khánh, Hà Nội' },
  { name: 'Tiệm Cơm Nàng Tấm',              phone: '0839103388', email: '',                               address: 'Khu đô thị Geleximco, Lê Trọng Tấn, Tây Mỗ, Hà Nội' },
  { name: 'Bún Đậu Thủy Gà',                phone: '0985102468', email: '',                               address: '201 Lê Trọng Tấn, La Dương, Dương Nội, Hà Nội' },
  { name: 'Tít Thò Lò',                     phone: '0972895533', email: '',                               address: '18AB, Dương Nội, Hà Nội' },
  { name: 'Cháo Mr.Bean',                   phone: '0862655924', email: '',                               address: 'Lê Giản, Đại Mỗ, Hà Nội, Vietnam' },
  { name: 'Tiệm Bánh Thu Trang',            phone: '0936290932', email: '',                               address: '49 P. Ngọc Trục, làng Ngọc Trục, Đại Mỗ, Hà Nội' },
  { name: "MỲ CAY LA'CA",                   phone: '0989251931', email: '',                               address: '40 P. Ngọc Trục, làng Ngọc Trục, Đại Mỗ, Hà Nội' },
  { name: 'Chân Gà Sốt Thái MeeChang',      phone: '0336789071', email: '',                               address: '93 Ngọc Trục, làng Ngọc Trục, Đại Mỗ, Hà Nội' },
  { name: 'Chất Lẩu Nướng Buffet',          phone: '0969158193', email: '',                               address: '48 Vườn Cam, Từ Liêm, Hà Nội' },
  { name: 'Quán nhậu Trang Trẻ Trâu',       phone: '0968598771', email: '',                               address: '6 P. Hồng Đô, làng Phú Đô, Từ Liêm, Hà Nội' },
  { name: 'Bia hơi minh tâm',               phone: '0836484333', email: '',                               address: '31 Đ. Mễ Trì, Từ Liêm, Hà Nội' },
  { name: 'Phở Thìn Mỹ Đình',               phone: '02432006379', email: '',                              address: 'CT9 Mỹ Đình Sông Đà, Từ Liêm, Hà Nội' },
  { name: 'Quán Tươi',                      phone: '0974356725', email: '',                               address: '3 Ngõ 123 Trung Kính, Yên Hòa, Hà Nội' },
  { name: 'Cơm Văn Đô Trung Kính',          phone: '0356922789', email: '',                               address: '58 P. Trung Kính, Yên Hòa, Hà Nội' },
  { name: 'KienKo Kitchen',                 phone: '0779222029', email: '',                               address: '34 P. Trung Kính, Yên Hòa, Hà Nội' },
  { name: 'Bún riêu tóp mỡ 37',             phone: '0961013130', email: '',                               address: '67 P. Trung Kính, Yên Hòa, Hà Nội' },
  { name: 'Đụt Quán',                       phone: '0868128180', email: '',                               address: '5 Ngõ 41 Trần Duy Hưng, Yên Hòa, Hà Nội' },
];

module.exports = USERS;
